# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.cache/wt [current_project]
set_property parent.project_path /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.srcs/sources_1/new/OutputLogic.v
  /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.srcs/sources_1/new/clk_div.v
  /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.srcs/sources_1/new/FSM.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.srcs/constrs_1/new/constraints_FSM.xdc
set_property used_in_implementation false [get_files /home/a5er/Documents/ETHZ/DoDC/Labs/Lab4/Lab4.srcs/constrs_1/new/constraints_FSM.xdc]


synth_design -top FSM -part xc7a35tcpg236-1


write_checkpoint -force -noxdef FSM.dcp

catch { report_utilization -file FSM_utilization_synth.rpt -pb FSM_utilization_synth.pb }
